Prepare MfccLogarithm
Revzik/Voice-Interface pull request #49
Opened 2020-11-29 18:59 UTC by AleksandraR177

2020-11-30 00:37 UTC, Revzik requested changes
Polecam jeszcze napisać test do tego polegający na np.: wygenerowaniu jakiegoś MelFrame z amplitudami 10, 100, 1000... i sprawdzeniu czy amplitudy będą 20, 40, 60...

2020-11-30 00:37 UTC, Revzik commented on src/param/mfcc.py
> +def MfccLogarithm (MelFrame):
To nie zadziała. "MelFrame" to nazwa klasy, więc nie możesz tak nazwać zmiennej. Poza tym w pythonie nazwy funkcji powinny być z małej litery i rozdzielane "_" (tutaj wystarczy logarithm)

2020-11-30 00:37 UTC, Revzik commented on src/param/mfcc.py
> +    MelFrame = 20 * np.log10(MelFrame)
Tutaj tak samo jak w przypadku naszych innych klas zawierających próbki musisz operować na atrybucie samples

2020-11-30 20:57 UTC, AleksandraR177 commented
update

2020-12-01 13:25 UTC, Revzik approved these changes

2020-12-01 21:48 UTC, merged